/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.carmotors;

import com.carmotors.interfaz.Customer;
import com.carmotors.interfaz.Inventory;
import com.carmotors.interfaz.Maintanence;
import com.carmotors.interfaz.Stats;
import com.carmotors.interfaz.Supplier;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author camper
 */
public class CarMotorsWorkshop extends javax.swing.JFrame {

    /**
     * Creates new form CarMotorsApp
     */
    public CarMotorsWorkshop() {
        initComponents();
        
       Inventory p1 = new Inventory();

       setResizable(false); // Deshabilita el redimensionamiento de la ventana

       
    }
    private void ShowPanel(JPanel p){
        p.setLocation(0, 0);
        article.removeAll();
        article.add(p,BorderLayout.CENTER);
        article.revalidate();
        article.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        Nav = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        inventory = new javax.swing.JButton();
        maintenance = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        suppliers = new javax.swing.JButton();
        Stats = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        article = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        bg.setLayout(new java.awt.BorderLayout());

        content.setBackground(new java.awt.Color(255, 204, 153));

        Nav.setBackground(new java.awt.Color(255, 153, 51));

        Title.setFont(new java.awt.Font("Waree", 1, 60)); // NOI18N
        Title.setText("CarMotors");

        inventory.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        inventory.setText("Gestion inventario");
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });

        maintenance.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        maintenance.setText("Mantenimiento y Reparaciones");
        maintenance.setActionCommand("");
        maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceActionPerformed(evt);
            }
        });

        customer.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        customer.setText("Clientes y Facturacion");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });

        suppliers.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        suppliers.setText("Proveedores y Compras");
        suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersActionPerformed(evt);
            }
        });

        Stats.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Stats.setText("Reportes y Estadisticas");
        Stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatsActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavLayout = new javax.swing.GroupLayout(Nav);
        Nav.setLayout(NavLayout);
        NavLayout.setHorizontalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppliers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Stats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NavLayout.createSequentialGroup()
                        .addComponent(exit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        NavLayout.setVerticalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit)
                .addGap(58, 58, 58)
                .addComponent(Title)
                .addGap(42, 42, 42)
                .addComponent(inventory)
                .addGap(12, 12, 12)
                .addComponent(maintenance)
                .addGap(18, 18, 18)
                .addComponent(customer)
                .addGap(18, 18, 18)
                .addComponent(suppliers)
                .addGap(18, 18, 18)
                .addComponent(Stats)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        article.setBackground(new java.awt.Color(0, 204, 153));
        article.setPreferredSize(new java.awt.Dimension(589, 800));
        article.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(Nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(article, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(article, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(content, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        Inventory p1 = new Inventory();
        ShowPanel(p1);
    }//GEN-LAST:event_inventoryActionPerformed

    private void maintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceActionPerformed
        Maintanence p2 = new Maintanence();
        ShowPanel(p2);
        
    }//GEN-LAST:event_maintenanceActionPerformed

    private void StatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatsActionPerformed
        Stats p3 = new Stats();
        ShowPanel(p3);
    }//GEN-LAST:event_StatsActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Estás seguro de que quieres salir?",
        "Confirmar salida",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_exitActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        Customer p4 = new Customer();
        ShowPanel(p4);
    }//GEN-LAST:event_customerActionPerformed

    private void suppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersActionPerformed
        Supplier p5 = new Supplier();
        ShowPanel(p5);
    }//GEN-LAST:event_suppliersActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarMotorsWorkshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarMotorsWorkshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarMotorsWorkshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarMotorsWorkshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarMotorsWorkshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nav;
    private javax.swing.JButton Stats;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel article;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JButton customer;
    private javax.swing.JButton exit;
    private javax.swing.JButton inventory;
    private javax.swing.JButton maintenance;
    private javax.swing.JButton suppliers;
    // End of variables declaration//GEN-END:variables
}
