/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.carmotors.inventory.view;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author camper
 */
public class GestionInvetory extends javax.swing.JPanel {

    /**
     * Creates new form Inventory
     */
    public GestionInvetory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Article = new javax.swing.JPanel();
        inventoryList = new javax.swing.JButton();
        sparePart = new javax.swing.JButton();
        report = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Article.setBackground(new java.awt.Color(255, 255, 255));

        inventoryList.setBackground(new java.awt.Color(0, 0, 0));
        inventoryList.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        inventoryList.setForeground(new java.awt.Color(255, 255, 255));
        inventoryList.setText("Inventario");
        inventoryList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventoryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryListActionPerformed(evt);
            }
        });

        sparePart.setBackground(new java.awt.Color(0, 0, 0));
        sparePart.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        sparePart.setForeground(new java.awt.Color(255, 255, 255));
        sparePart.setText("Repuesto");
        sparePart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sparePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparePartActionPerformed(evt);
            }
        });

        report.setBackground(new java.awt.Color(0, 0, 0));
        report.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("Reporte");
        report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión Inventario");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout ArticleLayout = new javax.swing.GroupLayout(Article);
        Article.setLayout(ArticleLayout);
        ArticleLayout.setHorizontalGroup(
            ArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArticleLayout.createSequentialGroup()
                .addGroup(ArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArticleLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(ArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inventoryList, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sparePart, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ArticleLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        ArticleLayout.setVerticalGroup(
            ArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArticleLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(inventoryList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(sparePart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Article, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Article, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryListActionPerformed
        inventoryList inventoryList = new inventoryList();
        
        ShowPanel(inventoryList);
    }//GEN-LAST:event_inventoryListActionPerformed

    private void ShowPanel(JPanel p){
        p.setLocation(0, 0);
        Article.removeAll();
        Article.add(p,BorderLayout.CENTER);
        Article.revalidate();
        Article.repaint();
    }
    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        report p3 = new report();
        ShowPanel(p3);
    }//GEN-LAST:event_reportActionPerformed

    private void sparePartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparePartActionPerformed
        sparePart p2 = new sparePart();
        ShowPanel(p2);
    }//GEN-LAST:event_sparePartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Article;
    private javax.swing.JButton inventoryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton report;
    private javax.swing.JButton sparePart;
    // End of variables declaration//GEN-END:variables
}
